version: "3.8"
services:
  backend:
    container_name: backend_enigma
    build:
      context: ./back/
      dockerfile: Dockerfile
    volumes:
      - ./back/:/go/src/
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true